import Head from "next/head";
import toast from 'react-hot-toast';

export default function Home() {
  return <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      Hello NextJS!
      <button onClick={()=>toast('Here is your toast.')}>test react-hot-toast</button>
      <button 
      onClick={()=>
      {const 
        promise = fetch('https://jsonplaceholder.typicode.com/users?'+Math.random); 
        toast.promise(promise,{
          loading: 'Loading',
          success: 'Got the data',
          error: 'Error when fetching',
        })}}>test toast promise</button>
    </main>
  </>;
}
